sonar.projectKey=Keerthan2006_ai-healthcare-application
sonar.organization=keerthan2006

sonar.sources=services/api
sonar.tests=services/api/tests

sonar.python.version=3.12

sonar.exclusions=services/api/tests/**
sonar.test.inclusions=services/api/tests/**/*.py

