apiVersion: v1
kind: Service
metadata:
  name: mock-ehr
  namespace: healthcare
spec:
  type: ClusterIP

  selector:
    app: mock-ehr

  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP