apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-service
  namespace: healthcare
  labels:
    app: ai-service

spec:
  replicas: {{ .Values.replicas.aiService }}

  selector:
    matchLabels:
      app: ai-service

  template:
    metadata:
      labels:
        app: ai-service

    spec:
      containers:
        - name: ai-service
          image: "{{ .Values.images.aiService.repository }}:{{ .Values.images.aiService.tag }}"

          ports:
            - containerPort: 8001

          envFrom:
            - configMapRef:
                name: ai-service-config

          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL