apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: healthcare
  labels:
    app: api-deploy
spec:
  replicas: {{ .Values.replicas.api }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: api-deploy
  template:
    metadata:
      labels:
        app: api-deploy
    spec:
      enableServiceLinks: false

      containers:
      - name: api
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: postgres-config
          - secretRef:
              name: postgres-secret
          - configMapRef:
              name: api-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL