apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker
  namespace: healthcare
  labels:
    app: worker

spec:
  replicas: {{ .Values.replicas.worker }}

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      enableServiceLinks: false

      containers:
        - name: worker
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.images.worker.repository }}:{{ .Values.images.worker.tag }}"

          ports:
            - containerPort: 8003
              protocol: TCP

          envFrom:
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: worker-config
            - secretRef:
                name: postgres-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL