replicas:
  api: 2
  aiService: 1
  worker: 1
  mockEhr: 1

images:
  api:
    repository: ""
    tag: "919daf0d84830235660636edd2610d2ce4db8834"

  aiService:
    repository: ""
    tag: ""

  worker:
    repository: ""
    tag: ""

  mockEhr:
    repository: ""
    tag: ""