global:
  imageRegistry: "181077295903.dkr.ecr.ap-south-1.amazonaws.com"
replicas:
  api: 2
  aiService: 1
  worker: 1
  mockEhr: 1

images:
  api:
    repository: "ai-healthcare-dev-api"
    tag: "919daf0d84830235660636edd2610d2ce4db8834"

  aiService:
    repository: "ai-healthcare-dev-ai-service"
    tag: "2b9a0e07566784c72a96e5d97160d5f2229424a0"

  worker:
    repository: "ai-healthcare-dev-worker"
    tag: "eb58201b8897f3045c825eff76447ea83ef81b40"

  mockEhr:
    repository: "ai-healthcare-dev-mock-ehr"
    tag: "7e352af53b63ea4d4a0eb51019d5a3f83b5e8247"
