name: API CI

on:
  push:
    branches:
      - main
    paths:
      - "services/api/**"
      - ".github/workflows/api-ci.yml"

  pull_request:
    branches:
      - main
    paths:
      - "services/api/**"
      - ".github/workflows/api-ci.yml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  api-ci:
    name: API CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: services/api/requirements.txt

      - name: Install dependencies
        working-directory: services/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff

      - name: Run Ruff
        working-directory: services/api
        run: |
          ruff check .

      - name: Run tests
        working-directory: services/api
        env:
          PYTHONPATH: .
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: ${{ vars.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ vars.DATABASE_DB }}
          AI_SERVICE_URL: http://localhost:8001
        run: |
          pytest

  sonarqube:
    name: SonarQube
    needs: api-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  docker:
    name: Docker Build and Trivy
    needs: sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ vars.ECR_REPOSITORY_API }}:${{ github.sha }} \
            ./services/api

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: ${{ vars.ECR_REPOSITORY_API }}:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true
  push-ecr:
    name: Push API Image to ECR
    needs: docker
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build API image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY_API }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            ./services/api

      - name: Push API image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY_API }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  update-tag:
    permissions:
      contents: write

    name: Update Helm Image Tag
    needs: push-ecr
    runs-on: ubuntu-latest

    env:
      SECRET: ${{ secrets.email }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update API image tag
        run: |
          sed -i '/^  api:/,/^  aiService:/ s/tag: .*/tag: "${{ github.sha }}"/' healthcare-platform/values.yaml

      - name: Show updated values
        run: |
          cat healthcare-platform/values.yaml

      - name: Git add-push
        run: |
          git config --global user.name "${{ vars.username }}"
          git config --global user.email "$SECRET"

          git add healthcare-platform/values.yaml

          git diff --cached --quiet || git commit -m "chore: update API image tag"

          git push